export CUDA_VISIBLE_DEVICES=0
model_name=SOFTS
python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_512_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 512 \
  --pred_len 96 \
  --e_layers 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --d_model 512 \
  --d_core 128 \
  --d_ff 512 \
  --batch_size 16 \
  --learning_rate 0.0003 \
  --train_epochs 50 \
  --patience 50 \
  --lradj cosine \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_512_192 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 512 \
  --pred_len 192 \
  --e_layers 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --d_model 512 \
  --d_core 128 \
  --d_ff 512 \
  --batch_size 16 \
  --learning_rate 0.0003 \
  --train_epochs 50 \
  --patience 50 \
  --lradj cosine \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_512_336 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 512 \
  --pred_len 336 \
  --e_layers 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --d_model 512 \
  --d_core 128 \
  --d_ff 512 \
  --batch_size 16 \
  --learning_rate 0.0003 \
  --train_epochs 50 \
  --patience 50 \
  --lradj cosine \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_512_720 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 512 \
  --pred_len 720 \
  --e_layers 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --d_model 512 \
  --d_core 128 \
  --d_ff 512 \
  --batch_size 16 \
  --learning_rate 0.0003 \
  --train_epochs 50 \
  --patience 50 \
  --lradj cosine \
  --des 'Exp' \
  --itr 1